name: Prevent DB Hibernation

env:
  ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}

on:
  schedule:
    - cron: '0 0 */2 * *' # every other day at midnight
jobs:
  resume_db:
    runs-on: ubuntu-latest
    steps:
      - name: Install Astra CLI
        run: |
          curl -Ls https://dtsx.io/get-astra-cli | bash
          source ~/.bash_profile
          astra setup --token $ASTRA_DB_APPLICATION_TOKEN
      - name: Get DB ID
        run: |
          DB_ID=$(curl -sS -L -X GET "https://api.astra.datastax.com/v2/databases" --header "Authorization: Bearer $ASTRA_DB_APPLICATION_TOKEN" --header "Content-Type: application/json" | jq '.[0].id')
      - name: Resume DB
        run: |
          astra db resume $DB_ID
