name: Prevent DB Hibernation

env:
  ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}

on:
  schedule:
    - cron: '0 0 * * 0-6/2' # every 2 days of the week, sunday through saturday at midnight
  workflow_dispatch:
jobs:
  resume_db:
    runs-on: macos-latest
    steps:
      - name: Install Astra CLI and Resume DB
        run: |
          export TERM=xterm
          curl -Ls https://dtsx.io/get-astra-cli | bash
          source ~/.bash_profile
          astra setup --token $ASTRA_DB_APPLICATION_TOKEN
          DB_ID=$(curl -sS -L -X GET "https://api.astra.datastax.com/v2/databases" --header "Authorization: Bearer $ASTRA_DB_APPLICATION_TOKEN" --header "Content-Type: application/json" | jq '.[0].id')
          astra db resume $DB_ID
